#cloud-config

package_update: true
package_upgrade: true

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDf69fjjLNdNaCGatVCzJEmnkiKUmxLbujS4+O0fpAU75WcNj6VsGs2WginUeSG9ADwCtUln8jiGSr4Keb2p/dkhkH0PfwExjz5nnJzifjeRyX3oP31ULXBiI9C0I5oP9Oxtdh6WLvx/J+GpWqxFCtKJyDrlIEmKL4qUJSeldobLfijamvjJtD5m9bXXs6mgk3XcPNwP5gEjPGSw395FSK/acC+k5h0lyf3HCmoQjJXyHN+4McLA9x7eT8mebNRSiEHi+eTFsZKyNFozZAuykyNFKY6Dt2h9scNNhEvt7gcFiInlXs14TOuJeYVjRupkJ2XYXvyYehZnwhn+lANi78RkMnqxf14N4w/eg0IxV/Tg610Ac2DjefT7eGKv69HBOC5P6Wq9MOAiXr8swWr13vnavSNJh13mk2QgVtfyBSABOgF2VbuQFGjyBSrnSeueZDpt8xPmABPcDNIzyUrgLKiNDmQ3rdSTwvF9BYosafp5aW6JOwtsv9WDnESSobee0vsbrepA/jebxN7SG54ir3GyaDEMpchzQmFZoUKzOjeA7U3AXauWOYyvKX96qX0ZnAWYz6lRi8hm770cCFkvPpWJiCVuY+0zf1iXSHpuUn6SrN2tkuA39ItJ0kinL78ESnmgA2XcFmO28FYHhzKdnJcc9EKTytAt0FIlAPxFGkmdw== danmauer@mac.lan

bootcmd:
  - modprobe overlay
  - modprobe br_netfilter

write_files:
  - path: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  - path: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables  = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward                 = 1
  - path: /etc/apt/keyrings/.placeholder
    content: ""

packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg
  - socat
  - conntrack
  - ipset

runcmd:
  # Disable swap
  - swapoff -a
  - sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

  # Apply sysctl settings
  - sysctl --system

  # Install containerd
  - |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    apt-get update
    apt-get install -y containerd.io

  # Configure containerd
  - mkdir -p /etc/containerd
  - containerd config default | tee /etc/containerd/config.toml
  - sed -i 's/SystemdCgroup = false/SystemdCgroup = true/' /etc/containerd/config.toml
  - systemctl restart containerd
  - systemctl enable containerd

  # Install Kubernetes packages
  - |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    echo "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /" | tee /etc/apt/sources.list.d/kubernetes.list
    apt-get update
    apt-get install -y kubelet kubeadm kubectl
    apt-mark hold kubelet kubeadm kubectl

  # Enable kubelet
  - systemctl enable kubelet

final_message: "Worker node initialization complete after $UPTIME seconds"
